version: '3.3'
services:
  mysql:
    env_file:
      - ./.env
    image: mysql:5.7
    # restart: always
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql_volume:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
