name: Release kozyol_frontend

on:
  push:
    branch: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: npm install and build webpack
        working-directory: ./client
        env:
          NODE_ENV: production
          REACT_APP_PROD_HOST: https://skazhi.be
        run: |
          npm install --production=false
          npm run build
      - uses: actions/upload-artifact@master
        with:
          name: frontend_dist
          path: client/build

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: build
    name: Docker Build, Tag, Push

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download built artifact
        uses: actions/download-artifact@main
        id: download_build
        with:
          name: frontend_dist
          path: client/build
      - name: 'Echo download path'
        run: echo ${{steps.download_build.outputs.download-path}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Echo current path'
        run: pwd
      - name: Build container and push image
        uses: docker/build-push-action@v2
        with:
          tags: |
            ghcr.io/${{github.actor}}/${{github.event.repository.name || 'kozyol-game'}}:${{github.sha}}
            ghcr.io/${{github.actor}}/${{github.event.repository.name || 'kozyol-game'}}:latest
          file: ./client/front.Dockerfile
          push: true